/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package marvel.api.auth

import java.time.Instant
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {


    @Test fun testAuthString() {
        val classUnderTest = Library()
        val result = classUnderTest.buildAuthString(Instant.now())
        println(result.toString())
    }
}
